apiName: "Kerstwebshop API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../client/dist/

server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/testDatabase
